export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'

export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const GET_POST = 'GET_POST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'

export const LOAD_POSTS_FROM_0_SUCCESS = 'LOAD_POSTS_FROM_0_SUCCESS'
export const LOAD_USER_POSTS_FROM_0_SUCCESS = 'LOAD_USER_POSTS_FROM_0_SUCCESS'
export const LOAD_SAVED_USER_POSTS_FROM_0_SUCCESS = 'LOAD_SAVED_USER_POSTS_FROM_0_SUCCESS'
export const LOAD_FINDED_POSTS_FROM_0_SUCCESS = 'LOAD_FINDED_POSTS_FROM_0_SUCCESS'

export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_USER_POSTS_SUCCESS = 'LOAD_USER_POSTS_SUCCESS'
export const LOAD_SAVED_USER_POSTS_SUCCESS = 'LOAD_SAVED_USER_POSTS_SUCCESS'
export const LOAD_FINDED_POSTS_SUCCESS = 'LOAD_FINDED_POSTS_SUCCESS'

export const LOAD_LATEST_USER_POSTS = 'LOAD_LATEST_USER_POSTS'
export const LOAD_OLDEST_USER_POSTS = 'LOAD_OLDEST_USER_POSTS'
export const LOAD_POPULAR_USER_POSTS = 'LOAD_POPULAR_USER_POSTS'
export const LOAD_SAVED_USER_POSTS = 'LOAD_SAVED_USER_POSTS'

export const LOAD_POPULAR_POSTS = 'LOAD_POSTS'
export const LOAD_LATEST_POSTS = 'LOAD_LATEST_POSTS'
export const LOAD_OLDEST_POSTS = 'LOAD_OLDEST_POSTS'

export const LOAD_FOLLOWED_POSTS = 'LOAD_FOLLOWED_POSTS'
export const LOAD_FOLLOWED_POSTS_SUCCESS = 'LOAD_FOLLOWED_POSTS_SUCCESS'
export const LOAD_FOLLOWED_POSTS_FROM_0_SUCCESS = 'LOAD_FOLLOWED_POSTS_FROM_0_SUCCESS'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'

export const LIKE_POST = 'LIKE_POST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'

export const SAVE_POST = 'SAVE_POST'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'

export const FIND_POST = 'FIND_POST'
export const FIND_POST_SUCCESS = 'FIND_POST_SUCCESS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_SUCCES = 'DELETE_COMMENT_SUCCESS'

export const LIKE_COMMENT = 'LIKE_COMMENT'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
