export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'

export const GET_POSTS_BY_TAG = 'GET_POSTS_BY_TAG'
export const GET_POSTS_BY_TAG_SUCCESS = 'GET_POSTS_BY_TAG_SUCCESS'
export const GET_POSTS_BY_TAG_FROM_0_SUCCESS = 'GET_POSTS_BY_TAG_FROM_0_SUCCESS'

export const GET_LATEST_POSTS_BY_TAG = 'GET_LATEST_POSTS_BY_TAG'
export const GET_POPULAR_POSTS_BY_TAG = 'GET_POPULAR_POSTS_BY_TAG'
export const GET_OLDEST_POSTS_BY_TAG = 'GET_OLDEST_POSTS_BY_TAG'

export const SET_TAG = 'SET_TAG'